services:
  mysql:
    image: mysql:8.0
    container_name: dental_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: dental_admin
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dental_network

  backend:
    build:
      context: ./backend-clean
      dockerfile: Dockerfile
    container_name: dental_backend
    restart: always
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: mysql
      DB_NAME: dental_admin
      DB_USER: root
      DB_PASSWORD:
      JWT_SECRET: tu_jwt_secret_muy_seguro
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - dental_network

volumes:
  mysql_data:

networks:
  dental_network:
    driver: bridge