sonar.projectKey=JohnMilos_Proyecto_Admin
sonar.organization=JohnMilos
sonar.host.url=https://sonarcloud.io

# Ruta del código fuente
sonar.sources=backend-clean/src

# Ruta de los tests
sonar.tests=backend-clean/tests

# Incluir también tests en el análisis
sonar.test.inclusions=**/*.test.js,**/*.spec.js

# Reporte de cobertura
sonar.javascript.lcov.reportPaths=backend-clean/coverage/lcov.info

# Excluir archivos que no quieres analizar
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/*.config.js,**/scripts/**,**/migrations/**

# Idioma
sonar.language=js
