sonar.projectKey=JohnMilos_Proyecto_Admin
sonar.organization=johnmilos
sonar.host.url=https://sonarcloud.io
sonar.sources=backend-clean/src
sonar.tests=backend-clean/tests
sonar.javascript.lcov.reportPaths=backend-clean/coverage/lcov.info
